# Generated by Django 2.0.6 on 2021-09-09 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('pk_categorias', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='foro',
            fields=[
                ('pk_foro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('link', models.URLField(max_length=250)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('pk_productos', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.BigIntegerField()),
                ('img', models.URLField(default='https://i.ibb.co/w7qB1Zf/Jake.png', max_length=8000)),
                ('fk_categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.categorias')),
                ('fk_foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.foro')),
            ],
        ),
    ]
