# Generated by Django 2.0.6 on 2021-08-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('pk_categorias', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='foro',
            fields=[
                ('pk_foro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('link', models.URLField(max_length=250)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('pk_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('pk_productos', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fk_categorias', models.ManyToManyField(to='webstore.categorias')),
                ('fk_foro', models.ManyToManyField(to='webstore.foro')),
                ('fk_marca', models.ManyToManyField(to='webstore.marca')),
            ],
        ),
        migrations.RemoveField(
            model_name='sell',
            name='fk_producto',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fk_producto',
        ),
        migrations.DeleteModel(
            name='producto',
        ),
        migrations.DeleteModel(
            name='sell',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
    ]
